"""board_pins.h for each MCU and the JSON model the simulator loads."""
import re

from .model import Node

BANNER = ('/* SPDX-License-Identifier: MIT */\n'
          '/* Generated by tools/build_board_model.py from the KiCad netlists and\n'
          ' * firmware/common/signals.json. Do not edit: change the schematic or the\n'
          ' * contract and regenerate. Pins follow the PCB as drawn (physical pads). */\n')


def _guard(path):
    return 'OSC_' + re.sub(r'\W', '_', path.split('/')[-1]).upper()


def header(checker, mcu, path):
    lines = [BANNER, f'#ifndef {_guard(path)}', f'#define {_guard(path)}', '']
    errors = {f.where[0] for f in checker.findings if f.severity == 'error' and f.where}
    for (m, name), r in sorted(checker.signals.items(), key=lambda kv: kv[1].spec['name']):
        if m != mcu:
            continue
        p = f'BOARD_{name}'
        if r.pin is None:
            lines += [f'/* {name}: sin resolver, ver sim/board-report.md */', '']
            continue
        note = ' /* revisar sim/board-report.md */' if str(r.pad) in errors else ''
        if mcu == 'stm32':
            port, num = r.pin[1], int(r.pin[2:])
            lines.append(f'#define {p}_PORT {ord(port) - ord("A")}u /* GPIO{port} */{note}')
            lines.append(f'#define {p}_PIN {num}u')
        else:
            lines.append(f'#define {p}_GPIO {int(r.pin[4:])}{note}')
        if 'active' in r.spec:
            lines.append(f'#define {p}_ACTIVE_HIGH {1 if r.spec["active"] == "high" else 0}')
        if r.af is not None:
            lines.append(f'#define {p}_AF {r.af}u /* {r.periph} */')
        if r.adc is not None:
            lines.append(f'#define {p}_ADC {r.adc[0]}u')
            lines.append(f'#define {p}_ADC_CHANNEL {r.adc[1]}u')
        lines.append('')
    done = [r.spec['name'] for (m, _), r in sorted(checker.signals.items(), key=lambda kv: kv[1].spec['name'])
            if m == mcu and r.pin is not None]
    lines.append('/* X-macro over every resolved signal, e.g. for init tables. */')
    cont = ' \\'
    lines.append('#define BOARD_SIGNALS(X)' + cont)
    lines += [f'    X({n})' + (cont if i < len(done) - 1 else '') for i, n in enumerate(done)]
    lines += ['', '#endif']
    return '\n'.join(lines) + '\n'


def model(checker):
    s = checker.s
    nets = {}
    for g, nodes in sorted(s.members.items()):
        nets[g] = {'aliases': s.aliases(g), 'rail': g in s.rails, 'volts': s.voltages.get(g),
                   'pins': sorted(str(n) for n in nodes)}
    comps = {}
    for board, b in s.boards.items():
        for ref, c in sorted(b.components.items()):
            comps[f'{board}:{ref}'] = {
                'part': c.part, 'value': c.value, 'mpn': c.mpn,
                'pins': {n: {'symbol': p.name, 'physical': s.physical_name(Node(board, ref, n)),
                             'net': s.net_of(Node(board, ref, n))}
                         for n, p in sorted(c.pins.items(), key=lambda kv: (len(kv[0]), kv[0]))}}
    signals = []
    for (mcu, name), r in sorted(checker.signals.items()):
        signals.append({'mcu': mcu, 'name': name, 'net': r.net, 'function': r.function,
                        'pad': str(r.pad) if r.pad else None, 'pin': r.pin, 'periph': r.periph,
                        'af': r.af, 'adc': list(r.adc) if r.adc else None, 'path': r.path,
                        'reset_level': r.reset_level})
    return {'_doc': 'Generated by tools/build_board_model.py; input of the F1 simulator.',
            'harness': s.contract['harness'], 'signals': signals, 'nets': nets, 'components': comps}
