/* SPDX-License-Identifier: MIT */
/* Generated by tools/build_board_model.py from the KiCad netlists and
 * firmware/common/signals.json. Do not edit: change the schematic or the
 * contract and regenerate. Pins follow the PCB as drawn (physical pads). */

#ifndef OSC_BOARD_PINS_H
#define OSC_BOARD_PINS_H

#define BOARD_KEY_INT_N_GPIO 6
#define BOARD_KEY_INT_N_ACTIVE_HIGH 0

#define BOARD_KEY_SCL_GPIO 5

#define BOARD_KEY_SDA_GPIO 4

#define BOARD_LCD_BL_GPIO 7
#define BOARD_LCD_BL_ACTIVE_HIGH 1

#define BOARD_LCD_CS_N_GPIO 10
#define BOARD_LCD_CS_N_ACTIVE_HIGH 0

#define BOARD_LCD_DC_GPIO 9

#define BOARD_LCD_MOSI_GPIO 11

#define BOARD_LCD_RST_N_GPIO 8
#define BOARD_LCD_RST_N_ACTIVE_HIGH 0

#define BOARD_LCD_SCLK_GPIO 12

#define BOARD_UART_RX_GPIO 2

#define BOARD_UART_TX_GPIO 42

#define BOARD_USB_DM_GPIO 19

#define BOARD_USB_DP_GPIO 20

#define BOARD_VBUS_SENSE_GPIO 15
#define BOARD_VBUS_SENSE_ACTIVE_HIGH 1

/* X-macro over every resolved signal, e.g. for init tables. */
#define BOARD_SIGNALS(X) \
    X(KEY_INT_N) \
    X(KEY_SCL) \
    X(KEY_SDA) \
    X(LCD_BL) \
    X(LCD_CS_N) \
    X(LCD_DC) \
    X(LCD_MOSI) \
    X(LCD_RST_N) \
    X(LCD_SCLK) \
    X(UART_RX) \
    X(UART_TX) \
    X(USB_DM) \
    X(USB_DP) \
    X(VBUS_SENSE)

#endif
