/* SPDX-License-Identifier: MIT */
/* Generated by tools/build_board_model.py from the KiCad netlists and
 * firmware/common/signals.json. Do not edit: change the schematic or the
 * contract and regenerate. Pins follow the PCB as drawn (physical pads). */

#ifndef OSC_BOARD_PINS_H
#define OSC_BOARD_PINS_H

#define BOARD_BREW_CURRENT_PORT 2u /* GPIOC */
#define BOARD_BREW_CURRENT_PIN 0u
#define BOARD_BREW_CURRENT_ADC 1u
#define BOARD_BREW_CURRENT_ADC_CHANNEL 6u

#define BOARD_BREW_DIR_PORT 2u /* GPIOC */
#define BOARD_BREW_DIR_PIN 14u
#define BOARD_BREW_DIR_ACTIVE_HIGH 1

#define BOARD_BREW_FAULT_N_PORT 1u /* GPIOB */
#define BOARD_BREW_FAULT_N_PIN 6u
#define BOARD_BREW_FAULT_N_ACTIVE_HIGH 0

#define BOARD_BREW_PWM_PORT 5u /* GPIOF */
#define BOARD_BREW_PWM_PIN 0u
#define BOARD_BREW_PWM_ACTIVE_HIGH 1
#define BOARD_BREW_PWM_AF 6u /* TIM1_CH3N */

#define BOARD_BREW_SLEEP_N_PORT 1u /* GPIOB */
#define BOARD_BREW_SLEEP_N_PIN 5u
#define BOARD_BREW_SLEEP_N_ACTIVE_HIGH 1

#define BOARD_BU_PRESENT_N_PORT 2u /* GPIOC */
#define BOARD_BU_PRESENT_N_PIN 2u
#define BOARD_BU_PRESENT_N_ACTIVE_HIGH 0

#define BOARD_BU_WORK_N_PORT 0u /* GPIOA */
#define BOARD_BU_WORK_N_PIN 0u
#define BOARD_BU_WORK_N_ACTIVE_HIGH 0

#define BOARD_DOOR_CLOSED_N_PORT 0u /* GPIOA */
#define BOARD_DOOR_CLOSED_N_PIN 1u
#define BOARD_DOOR_CLOSED_N_ACTIVE_HIGH 0

#define BOARD_FLOW_PORT 0u /* GPIOA */
#define BOARD_FLOW_PIN 2u
#define BOARD_FLOW_ACTIVE_HIGH 0
#define BOARD_FLOW_AF 1u /* TIM2_CH3 */

#define BOARD_GRINDER_CURRENT_PORT 0u /* GPIOA */
#define BOARD_GRINDER_CURRENT_PIN 6u
#define BOARD_GRINDER_CURRENT_ADC 2u
#define BOARD_GRINDER_CURRENT_ADC_CHANNEL 3u

#define BOARD_GRINDER_EN_PORT 2u /* GPIOC */
#define BOARD_GRINDER_EN_PIN 4u
#define BOARD_GRINDER_EN_ACTIVE_HIGH 1

#define BOARD_HEATER_EN_PORT 2u /* GPIOC */
#define BOARD_HEATER_EN_PIN 5u
#define BOARD_HEATER_EN_ACTIVE_HIGH 1

#define BOARD_MAINS_ARM_PORT 1u /* GPIOB */
#define BOARD_MAINS_ARM_PIN 7u
#define BOARD_MAINS_ARM_ACTIVE_HIGH 1

#define BOARD_NTC_PORT 0u /* GPIOA */
#define BOARD_NTC_PIN 3u
#define BOARD_NTC_ADC 1u
#define BOARD_NTC_ADC_CHANNEL 4u

#define BOARD_PUMP_EN_PORT 1u /* GPIOB */
#define BOARD_PUMP_EN_PIN 11u
#define BOARD_PUMP_EN_ACTIVE_HIGH 1

#define BOARD_RAIL_12V_PORT 5u /* GPIOF */
#define BOARD_RAIL_12V_PIN 1u
#define BOARD_RAIL_12V_ADC 2u
#define BOARD_RAIL_12V_ADC_CHANNEL 10u

#define BOARD_RAIL_24V_PORT 2u /* GPIOC */
#define BOARD_RAIL_24V_PIN 1u
#define BOARD_RAIL_24V_ADC 1u
#define BOARD_RAIL_24V_ADC_CHANNEL 7u

#define BOARD_UART_RX_PORT 0u /* GPIOA */
#define BOARD_UART_RX_PIN 10u
#define BOARD_UART_RX_AF 7u /* USART1_RX */

#define BOARD_UART_TX_PORT 0u /* GPIOA */
#define BOARD_UART_TX_PIN 9u
#define BOARD_UART_TX_AF 7u /* USART1_TX */

#define BOARD_UI_PWR_EN_PORT 1u /* GPIOB */
#define BOARD_UI_PWR_EN_PIN 12u
#define BOARD_UI_PWR_EN_ACTIVE_HIGH 1

#define BOARD_VALVE_EN_PORT 0u /* GPIOA */
#define BOARD_VALVE_EN_PIN 7u
#define BOARD_VALVE_EN_ACTIVE_HIGH 1

#define BOARD_WATER_LEVEL_PORT 2u /* GPIOC */
#define BOARD_WATER_LEVEL_PIN 3u
#define BOARD_WATER_LEVEL_ADC 1u
#define BOARD_WATER_LEVEL_ADC_CHANNEL 9u

#define BOARD_WDT_KICK_PORT 1u /* GPIOB */
#define BOARD_WDT_KICK_PIN 4u
#define BOARD_WDT_KICK_ACTIVE_HIGH 1

/* X-macro over every resolved signal, e.g. for init tables. */
#define BOARD_SIGNALS(X) \
    X(BREW_CURRENT) \
    X(BREW_DIR) \
    X(BREW_FAULT_N) \
    X(BREW_PWM) \
    X(BREW_SLEEP_N) \
    X(BU_PRESENT_N) \
    X(BU_WORK_N) \
    X(DOOR_CLOSED_N) \
    X(FLOW) \
    X(GRINDER_CURRENT) \
    X(GRINDER_EN) \
    X(HEATER_EN) \
    X(MAINS_ARM) \
    X(NTC) \
    X(PUMP_EN) \
    X(RAIL_12V) \
    X(RAIL_24V) \
    X(UART_RX) \
    X(UART_TX) \
    X(UI_PWR_EN) \
    X(VALVE_EN) \
    X(WATER_LEVEL) \
    X(WDT_KICK)

#endif
